main: net.teamfekker.tfstaffmode.Main
name: TFIStaffMode
version: 1.0
api-version: 1.16
depend: [GroupManager]
description: Enables TFI StaffMode!
authors: [BearTrafalgar, GabeTrafalgar]
website: www.teamfekker.net
